version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: placeholder
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    ports: 
      - "5000:5000"
    environment:
      APP_PORT: 5000
      DATABASE_URL: mongodb://mongodb:27017/
    depends_on:
      - mongodb

volumes:
  mongo-data: